---
title: "model-building-svyglm"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#load libraries
library(tidyverse)
library(srvyr)
library(survey)
library(broom)
library(openxlsx)
library(usmap)
```

```{r}
#load data
data_20 <- read_csv("data/cps_csv_files/2020 cps.csv")
data_18 <- read_csv("data/cps_csv_files/2018 cps.csv")
data_16 <- read_csv("data/cps_csv_files/2016 cps.csv")
data_14 <- read_csv("data/cps_csv_files/2014 cps.csv")
data_12 <- read_csv("data/cps_csv_files/2012 cps.csv")
data_10 <- read_csv("data/cps_csv_files/2010 cps.csv")
data_total <- read_csv("data/cps_csv_files/master.csv")

vep_20 <- read_csv("data/2020 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%", "", total_ballot))/100)
vep_18 <- read_csv("data/2018 VEP.csv")|>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%", "", total_ballot))/100)
vep_16 <- read_csv("data/2016 VEP.csv")|>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%", "", total_ballot))/100)
vep_14 <- read_csv("data/2014 VEP.csv")|>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%", "", total_ballot))/100)
vep_12 <- read_csv("data/2012 VEP.csv")|>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%", "", total_ballot))/100)
vep_10 <- read_csv("data/2010 VEP.csv")|>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%", "", total_ballot))/100)
```

```{r}
#clean data

#2010 DATA
data_10 <- data_10 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial") |>
    factor(levels = c("White", "Black", "AmIn", "AAPI", "Multi-racial")),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic") |>
    factor(levels = c("Not Hispanic", "Hispanic")), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU") |>
    factor(levels = c("No", "Yes")), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU")|>
    factor(levels = c("NIU", "No HS", "HS", "Some College", "Beyond Bachelors")),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+") |>
    factor(levels = c("18-29", "30-44", "45-64", "65+")),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("No", "Yes"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)

#2012 DATA

data_12 <- data_12 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial")  |>
    factor(levels = c("White", "Black", "AmIn", "AAPI", "Multi-racial")),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic") |>
    factor(levels = c("Not Hispanic", "Hispanic")), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU") |>
    factor(levels = c("No", "Yes")), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU") |>
    factor(levels = c("NIU", "No HS", "HS", "Some College", "Beyond Bachelors")),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+") |>
    factor(levels = c("18-29", "30-44", "45-64", "65+")),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("No", "Yes"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)

#2014 DATA

data_14 <- data_14 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial")  |>
    factor(levels = c("White", "Black", "AmIn", "AAPI", "Multi-racial")),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic") |>
    factor(levels = c("Not Hispanic", "Hispanic")), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU") |>
    factor(levels = c("No", "Yes")), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU") |>
    factor(levels = c("NIU", "No HS", "HS", "Some College", "Beyond Bachelors")),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+") |>
    factor(levels = c("18-29", "30-44", "45-64", "65+")),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("No", "Yes"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)

#2016 DATA

data_16 <- data_16 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial")  |>
    factor(levels = c("White", "Black", "AmIn", "AAPI", "Multi-racial")),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic") |>
    factor(levels = c("Not Hispanic", "Hispanic")), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU") |>
    factor(levels = c("No", "Yes")), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU") |>
    factor(levels = c("NIU", "No HS", "HS", "Some College", "Beyond Bachelors")),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+") |>
    factor(levels = c("18-29", "30-44", "45-64", "65+")),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("No", "Yes"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)

#2018 DATA

data_18 <- data_18 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial") |>
    factor(levels = c("White", "Black", "AmIn", "AAPI", "Multi-racial")),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic") |>
    factor(levels = c("Not Hispanic", "Hispanic")), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU") |>
    factor(levels = c("No", "Yes")), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU") |>
    factor(levels = c("NIU", "No HS", "HS", "Some College", "Beyond Bachelors")),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+") |>
    factor(levels = c("18-29", "30-44", "45-64", "65+")),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("No", "Yes"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)

#2020 DATA

data_20 <- data_20 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial") |>
    factor(levels = c("White", "Black", "AmIn", "AAPI", "Multi-racial")),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic") |>
    factor(levels = c("Not Hispanic", "Hispanic")), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU") |>
    factor(levels = c("No", "Yes")), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU") |>
    factor(levels = c("NIU", "No HS", "HS", "Some College", "Beyond Bachelors")),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+") |>
    factor(levels = c("18-29", "30-44", "45-64", "65+")),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("No", "Yes")),
         EDUC = factor(EDUC, levels = c("No HS", "HS", "Some College", "Beyond Bachelors"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)


ids <- c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56)
states <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming")

states_df <- data.frame(ids, as.factor(states))

names(states_df) <- c('STATEFIP', 'STATE')

data_10 <- merge(data_10, states_df, by="STATEFIP", all = FALSE)
data_12 <- merge(data_12, states_df, by="STATEFIP", all = FALSE)
data_14 <- merge(data_14, states_df, by="STATEFIP", all = FALSE)
data_16 <- merge(data_16, states_df, by="STATEFIP", all = FALSE)
data_18 <- merge(data_18, states_df, by="STATEFIP", all = FALSE)
data_20 <- merge(data_20, states_df, by="STATEFIP", all = FALSE)
data_total <- merge(data_total, states_df, by="STATEFIP", all = FALSE)
```

```{r}
#create hur and achen weights

#2010 data
data_10_weighted <- data_10 |>
  as_survey_design(weights = VOSUPPWT)

turnout_10 <- data_10_weighted |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

turnout_weights_10 <- turnout_10 |>
  left_join(vep_10, by = "STATE") |>
  mutate(weight_nonvoter_num = 1 - total_ballot,
         weight_nonvoter_denom = 1 - turnout,
         weight_voter = total_ballot/turnout,
         weight_nonvoter = weight_nonvoter_num/weight_nonvoter_denom) |>
  select(STATE, weight_nonvoter, weight_voter)

augmented_data_10 <- data_10 |>
  left_join(turnout_weights_10, by = "STATE") |>
  mutate(ADJ_VOSUPPWT = case_when(VOTED == "Yes" ~ VOSUPPWT * weight_voter,
                                  VOTED == "No" ~ VOSUPPWT * weight_nonvoter),
         STATE = factor(STATE, levels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"))) |>
  select(STATE, AGE, EDUC, RACE, HISPAN, ADJ_VOSUPPWT, DIFFANY, VOTED)

hurachen_data_10 <- augmented_data_10 |>
  as_survey_design(weights = ADJ_VOSUPPWT)

hurachen_turnout_10 <- hurachen_data_10 |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))
#2012 data
data_12_weighted <- data_12 |>
  as_survey_design(weights = VOSUPPWT)

turnout_12 <- data_12_weighted |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

turnout_weights_12 <- turnout_12 |>
  left_join(vep_12, by = "STATE") |>
  mutate(weight_nonvoter_num = 1 - total_ballot,
         weight_nonvoter_denom = 1 - turnout,
         weight_voter = total_ballot/turnout,
         weight_nonvoter = weight_nonvoter_num/weight_nonvoter_denom) |>
  select(STATE, weight_nonvoter, weight_voter)

augmented_data_12 <- data_12 |>
  left_join(turnout_weights_12, by = "STATE") |>
  mutate(ADJ_VOSUPPWT = case_when(VOTED == "Yes" ~ VOSUPPWT * weight_voter,
                                  VOTED == "No" ~ VOSUPPWT * weight_nonvoter),
         STATE = factor(STATE, levels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"))) |>
  select(STATE, AGE, EDUC, RACE, HISPAN, ADJ_VOSUPPWT, DIFFANY, VOTED)

hurachen_data_12 <- augmented_data_12 |>
  as_survey_design(weights = ADJ_VOSUPPWT)

hurachen_turnout_12 <- hurachen_data_12 |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))
#2014 data
data_14_weighted <- data_14 |>
  as_survey_design(weights = VOSUPPWT)

turnout_14 <- data_14_weighted |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

turnout_weights_14 <- turnout_14 |>
  left_join(vep_14, by = "STATE") |>
  mutate(weight_nonvoter_num = 1 - total_ballot,
         weight_nonvoter_denom = 1 - turnout,
         weight_voter = total_ballot/turnout,
         weight_nonvoter = weight_nonvoter_num/weight_nonvoter_denom) |>
  select(STATE, weight_nonvoter, weight_voter)

augmented_data_14 <- data_14 |>
  left_join(turnout_weights_14, by = "STATE") |>
  mutate(ADJ_VOSUPPWT = case_when(VOTED == "Yes" ~ VOSUPPWT * weight_voter,
                                  VOTED == "No" ~ VOSUPPWT * weight_nonvoter),
         STATE = factor(STATE, levels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"))) |>
  select(STATE, AGE, EDUC, RACE, HISPAN, ADJ_VOSUPPWT, DIFFANY, VOTED)

hurachen_data_14 <- augmented_data_14 |>
  as_survey_design(weights = ADJ_VOSUPPWT)

hurachen_turnout_14 <- hurachen_data_14 |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))
#2016 data
data_16_weighted <- data_16 |>
  as_survey_design(weights = VOSUPPWT)

turnout_16 <- data_16_weighted |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

turnout_weights_16 <- turnout_16 |>
  left_join(vep_16, by = "STATE") |>
  mutate(weight_nonvoter_num = 1 - total_ballot,
         weight_nonvoter_denom = 1 - turnout,
         weight_voter = total_ballot/turnout,
         weight_nonvoter = weight_nonvoter_num/weight_nonvoter_denom) |>
  select(STATE, weight_nonvoter, weight_voter)

augmented_data_16 <- data_16 |>
  left_join(turnout_weights_16, by = "STATE") |>
  mutate(ADJ_VOSUPPWT = case_when(VOTED == "Yes" ~ VOSUPPWT * weight_voter,
                                  VOTED == "No" ~ VOSUPPWT * weight_nonvoter),
         STATE = factor(STATE, levels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"))) |>
  select(STATE, AGE, EDUC, RACE, HISPAN, ADJ_VOSUPPWT, DIFFANY, VOTED)

hurachen_data_16 <- augmented_data_16 |>
  as_survey_design(weights = ADJ_VOSUPPWT)

hurachen_turnout_16 <- hurachen_data_16 |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))
#2018 data
data_18_weighted <- data_18 |>
  as_survey_design(weights = VOSUPPWT)

turnout_18 <- data_18_weighted |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

turnout_weights_18 <- turnout_18 |>
  left_join(vep_18, by = "STATE") |>
  mutate(weight_nonvoter_num = 1 - total_ballot,
         weight_nonvoter_denom = 1 - turnout,
         weight_voter = total_ballot/turnout,
         weight_nonvoter = weight_nonvoter_num/weight_nonvoter_denom) |>
  select(STATE, weight_nonvoter, weight_voter)

augmented_data_18 <- data_18 |>
  left_join(turnout_weights_18, by = "STATE") |>
  mutate(ADJ_VOSUPPWT = case_when(VOTED == "Yes" ~ VOSUPPWT * weight_voter,
                                  VOTED == "No" ~ VOSUPPWT * weight_nonvoter),
         STATE = factor(STATE, levels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"))) |>
  select(STATE, AGE, EDUC, RACE, HISPAN, ADJ_VOSUPPWT, DIFFANY, VOTED)

hurachen_data_18 <- augmented_data_18 |>
  as_survey_design(weights = ADJ_VOSUPPWT)

hurachen_turnout_18 <- hurachen_data_18 |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

#2020 data
data_20_weighted <- data_20 |>
  as_survey_design(weights = VOSUPPWT)

turnout_20 <- data_20_weighted |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

turnout_weights_20 <- turnout_20 |>
  left_join(vep_20, by = "STATE") |>
  mutate(weight_nonvoter_num = 1 - total_ballot,
         weight_nonvoter_denom = 1 - turnout,
         weight_voter = total_ballot/turnout,
         weight_nonvoter = weight_nonvoter_num/weight_nonvoter_denom) |>
  select(STATE, weight_nonvoter, weight_voter)

augmented_data_20 <- data_20 |>
  left_join(turnout_weights_20, by = "STATE") |>
  mutate(ADJ_VOSUPPWT = case_when(VOTED == "Yes" ~ VOSUPPWT * weight_voter,
                                  VOTED == "No" ~ VOSUPPWT * weight_nonvoter),
         STATE = factor(STATE, levels = c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"))) |>
  select(STATE, AGE, EDUC, RACE, HISPAN, ADJ_VOSUPPWT, DIFFANY, VOTED)

hurachen_data_20 <- augmented_data_20 |>
  as_survey_design(weights = ADJ_VOSUPPWT)

hurachen_turnout_20 <- hurachen_data_20 |>
  group_by(STATE) |>
  summarize(turnout = survey_mean(VOTED == "Yes", na.rm = TRUE))

master_hurachen_data <- rbind(augmented_data_10, augmented_data_12, augmented_data_14, augmented_data_16, augmented_data_18, augmented_data_20)

master_hurachen <- master_hurachen_data|>
  as_survey_design(weights = ADJ_VOSUPPWT)
```

```{r}
#| eval: false
#look for interactions

#state, age
data_total |>
  group_by(AGE, STATE) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = STATE, y = age_diffany_turnout, color = AGE)) +
  geom_point()

#state, ethnicity
data_total |>
  group_by(HISPAN, STATE) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = STATE, y = age_diffany_turnout, color = HISPAN)) +
  geom_point()

#state, disability
data_total |>
  group_by(DIFFANY, STATE) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = STATE, y = age_diffany_turnout, color = DIFFANY)) +
  geom_point()
#state, educ
data_total |>
  group_by(EDUC, STATE) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = STATE, y = age_diffany_turnout, color = EDUC)) +
  geom_point()
#state, race
data_total |>
  group_by(RACE, STATE) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = STATE, y = age_diffany_turnout, color = RACE)) +
  geom_point()

#no interaction between age, disability
data_total |>
  group_by(AGE, DIFFANY) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = AGE, y = age_diffany_turnout, color = DIFFANY)) +
  geom_point() +
  geom_path(aes(group = interaction(AGE, DIFFANY)))

# no interaction between age, ethnicity
data_total |>
  group_by(AGE, HISPAN) |>
  summarize(age_hispan_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = AGE, y = age_hispan_turnout, color = HISPAN)) +
  geom_point()

# none age, education
data_total |>
  group_by(AGE, EDUC) |>
  summarize(age_educ_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = AGE, y = age_educ_turnout, color = EDUC)) +
  geom_point()

# age, race FOUND INTERACTION
data_total |>
  group_by(AGE, RACE) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = AGE, y = age_race_turnout, color = RACE)) +
  geom_point()

# ethnicity, disability
data_total |>
  group_by(HISPAN, DIFFANY) |>
  summarize(age_diffany_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = HISPAN, y = age_diffany_turnout, color = DIFFANY)) +
  geom_point() +
  geom_path(aes(group = interaction(HISPAN, DIFFANY)))

# ethnicity, education
data_total |>
  group_by(HISPAN, EDUC) |>
  summarize(age_educ_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = HISPAN, y = age_educ_turnout, color = EDUC)) +
  geom_point()

# ethnicity, race FOUND INTERACTION
data_total |>
  group_by(HISPAN, RACE) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = HISPAN, y = age_race_turnout, color = RACE)) +
  geom_point()

# race, disability
data_total |>
  group_by(RACE, DIFFANY) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = DIFFANY, y = age_race_turnout, color = RACE)) +
  geom_point()

# race, education IT EXISTS!
data_total |>
  group_by(RACE, EDUC) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = EDUC, y = age_race_turnout, color = RACE)) +
  geom_point()

# disability, education
data_total |>
  group_by(DIFFANY, EDUC) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = EDUC, y = age_race_turnout, color = DIFFANY)) +
  geom_point()

# age, ethnicity, race YES
data_total |>
  group_by(DIFFANY, AGE, RACE) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = AGE, y = age_race_turnout, color = RACE)) +
  geom_point() +
  facet_wrap(vars(DIFFANY))

# race, education, ethnicity YES
data_total |>
  group_by(EDUC, HISPAN, RACE) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = EDUC, y = age_race_turnout, color = RACE)) +
  geom_point() +
  facet_wrap(vars(HISPAN))

# race, age, disability NO
data_total |>
  group_by(AGE, DIFFANY, RACE) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = AGE, y = age_race_turnout, color = RACE)) +
  geom_point() +
  facet_wrap(vars(DIFFANY))

#race, ethnicity, disability YES
data_total |>
  group_by(DIFFANY, HISPAN, RACE) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = DIFFANY, y = age_race_turnout, color = RACE)) +
  geom_point() +
  facet_wrap(vars(HISPAN))

#educ, ethnicity, disability YES
data_total |>
  group_by(DIFFANY, HISPAN, EDUC) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = EDUC, y = age_race_turnout, color = DIFFANY)) +
  geom_point() +
  facet_wrap(vars(HISPAN))

#educ, race, age

data_total |>
  group_by(AGE, RACE, EDUC) |>
  summarize(age_race_turnout = sum(VOTED == "Yes")/n()) |>
  ggplot(aes(x = EDUC, y = age_race_turnout, color = AGE)) +
  geom_point() +
  facet_wrap(vars(RACE))
```

```{r}
#MODELLING RACE BY STATE

state_race_var <- states_df |>
  select(STATE) |>
  mutate(STATEFIP = NA) |>
  rename(cum_var = STATEFIP)

model_state_race <- function(states) {
  for (i in 1:51) {
    statename = states[i]
    state_subset <- master_hurachen_data |>
      filter(STATE == statename)
    
    state_subset_survey <- state_subset |>
      as_survey_design(weights = ADJ_VOSUPPWT)
    
    state_model <- svyglm(formula = VOTED ~ RACE + HISPAN, design = state_subset_survey, family = quasibinomial)
    state_tidy <- tidy(state_model) |>
      mutate(odds = exp(estimate)) |>
      add_column(demographics = c(0.593, 0.126, .013, 0.064, 0.029, 0.189)) |>
      mutate(weighted_var = ((100-100*odds)^2 * demographics))
    
    cum_var <- state_tidy |>
      filter(term != "(Intercept)") |>
      select(weighted_var) |>
      pull()

    state_race_var$cum_var[i] <- sum(cum_var)
    
    assign(x = paste0(statename, "race_model"), value = state_tidy, envir = globalenv())
  }
}

model_state_race(states)

state_race_var$cum_var[1:51] <- c(1042.826, 880.1261, 956.9159, 952.2599, 846.3041, 1574.574,
                                  829.2937, 978.1449, 370.6585, 594.1218, 851.4276, 738.2611,
                                  1415.243, 783.815, 637.0096, 1022.17, 950.6924, 825.1885,
                                  518.5864, 1178.291, 497.994, 1353.358, 578.9438, 984.3383,
                                  1135.824, 480.9531, 1077.472, 1341.855, 609.8921, 936.0061,
                                  377.0212, 1283.383, 603.8181, 429.1207, 1787.471, 453.1162,
                                  1075.9, 1370.818, 942.4105, 550.5834, 1027.237, 1510.367,
                                  655.0294, 856.7501, 1217.279, 682.321, 474.0115, 1255.164,
                                  764.3268, 1008.249, 580.6082)

```

```{r}
#MODELLING AGE BY STATE

state_age_var <- states_df |>
  select(STATE) |>
  mutate(STATEFIP = NA) |>
  rename(cum_var = STATEFIP)

model_state_age <- function(states) {
  for (i in 1:51) {
    statename = states[i]
    state_subset <- master_hurachen_data |>
      filter(STATE == statename)
    
    state_subset_survey <- state_subset |>
      as_survey_design(weights = ADJ_VOSUPPWT)
    
    state_model <- svyglm(formula = VOTED ~ AGE, design = state_subset_survey, family = quasibinomial)
    state_tidy <- tidy(state_model) |>
      mutate(odds = exp(estimate)) |>
      add_column(demographics = c(0.161, 0.195, 0.251, 0.168)) |>
      mutate(weighted_var = ((100-100*odds)^2 * demographics))
    
    cum_var <- state_tidy |>
      filter(term != "(Intercept)") |>
      select(weighted_var) |>
      pull()

    print(sum(cum_var))
    
    assign(x = paste0(statename, "age_model"), value = state_tidy, envir = globalenv())
  }
}

model_state_age(states)
state_age_var$cum_var[1:51] <- c(16358.9, 64382.84, 42743.36, 38317.79, 16478.04, 71622.66, 32723.04, 36423.26, 1710.136, 39374.53, 20330.46, 40308.42, 41810.99, 30850.55, 27767.67, 47530.26, 53554.57, 18223.05, 26131.51, 56532.95, 14196.01, 31803.63, 55781.13, 21676.45, 18329.17, 16100.23, 89606.19, 39276.73, 25940.59, 30351.75, 17850.56, 43001.19, 13941.88, 26223.3, 31392.87, 29681.77, 66539.53, 40469.53, 14371.53, 23511.25, 17847.99, 74855.77, 22674.95, 45773.69, 44790.3, 47077.9, 13252.78, 53864.31, 28771.02, 31908.32, 44942.88)

```

```{r}
#MODELLING EDUC BY STATE

state_educ_var <- states_df |>
  select(STATE) |>
  mutate(STATEFIP = NA) |>
  rename(cum_var = STATEFIP)

model_state_educ <- function(states) {
  for (i in 1:51) {
    statename = states[i]
    state_subset <- master_hurachen_data |>
      filter(STATE == statename)
    
    state_subset_survey <- state_subset |>
      as_survey_design(weights = ADJ_VOSUPPWT)
    
    state_model <- svyglm(formula = VOTED ~ EDUC, design = state_subset_survey, family = quasibinomial)
    state_tidy <- tidy(state_model) |>
      mutate(odds = exp(estimate)) |>
      add_column(demographics = c(0.089, 0.279, 0.489, 0.144)) |>
      mutate(weighted_var = ((100-100*odds)^2 * demographics))
    
    cum_var <- state_tidy |>
      filter(term != "(Intercept)") |>
      select(weighted_var) |>
      pull()

    print(sum(cum_var))
    
    assign(x = paste0(statename, "educ_model"), value = state_tidy, envir = globalenv())
  }
}

model_state_educ(states)
state_educ_var$cum_var[1:51] <- c(122951.4, 395038.7, 241144, 231388.6, 97789.03, 512768.6, 92656.64, 298495.4, 88886.91, 109733.7, 239136.3, 235639.1, 420170.9, 148166.7, 363036, 270252.9, 492691.6, 263878.5, 143092.7, 621571.4, 125837.2, 114107.4, 327116.5, 331427.2, 55580.65, 255475.7, 365601.6, 190181.1, 174932.7, 232691.4, 36404.59, 218301.9, 73943.56, 154590.3,93360.66, 194165.3, 440292.5, 320685.6, 402969.4, 249467.8, 349775.4, 157648.1, 210860.5, 115433.7, 137906.3, 979509.1, 169322.1, 464833.3, 441137.9, 353311.2, 187583.8)

```

```{r}
#MODELLING DISAB BY STATE

state_diffany_var <- states_df |>
  select(STATE) |>
  mutate(STATEFIP = NA) |>
  rename(cum_var = STATEFIP)

model_state_diffany <- function(states) {
  for (i in 1:51) {
    statename = states[i]
    state_subset <- master_hurachen_data |>
      filter(STATE == statename)
    
    state_subset_survey <- state_subset |>
      as_survey_design(weights = ADJ_VOSUPPWT)
    
    state_model <- svyglm(formula = VOTED ~ DIFFANY, design = state_subset_survey, family = quasibinomial)
    state_tidy <- tidy(state_model) |>
      mutate(odds = exp(estimate)) |>
      add_column(demographics = c(0.873, 0.127)) |>
      mutate(weighted_var = ((100-100*odds)^2 * demographics))
    
    cum_var <- state_tidy |>
      filter(term != "(Intercept)") |>
      select(weighted_var) |>
      pull()

    print(sum(cum_var))
    
    assign(x = paste0(statename, "diffany_model"), value = state_tidy, envir = globalenv())
  }
}

model_state_diffany(states)

state_diffany_var$cum_var[1:51] <- c(161.8999, 36.59372, 0.09027836, 124.5696, 86.26168, 68.79365, 89.05811, 160.7877, 303.486, 55.43179, 148.7247, 12.58138, 55.14489, 41.89386, 134.3203, 105.7116, 41.84036, 178.6247, 154.1225, 185.1109, 249.7392, 214.4344, 76.0655, 228.714, 86.94751, 155.0795, 60.23558, 11.22952, 5.314265, 135.5375, 182.8238, 25.23924, 189.2113, 135.6275, 50.22619, 140.6865, 46.05318, 113.5406, 147.0222, 93.78531, 188.3773, 64.47568, 260.5009, 22.85726, 4.028968, 149.0351, 202.6527, 59.28687, 145.1491, 166.5978, 62.66779)
```

```{r}

#graph results

#race map
states_race_map <- us_map(regions = "states") |>
  full_join(state_race_var, by = c("full" = "STATE"))

race_plot <- ggplot(data = states_race_map, aes(x = x, y = y, group = group)) +
  geom_polygon(aes(fill = cum_var), color = "black", linewidth = 0.5) +
  scale_fill_gradient(low = "white", high = "#DC582A",
                      guide_colorbar(frame.color = "black", frame.linewidth = 0.5)) +
  labs(title = "Differences in intrastate predicted turnout among racial and ethnic groups",
       subtitle = "Colors represent variance in turnout odds",
       caption = "Using Census-designated racial and ethnic groups\n and 2010-2020 CPS Voting Supplement data.") +
  theme_void() +
  theme(legend.position = "none")
  

race_plot

#age map
states_age_map <- us_map(regions = "states") |>
  full_join(state_age_var, by = c("full" = "STATE"))

age_plot <- ggplot(data = states_age_map, aes(x = x, y = y, group = group)) +
  geom_polygon(aes(fill = cum_var), color = "black", linewidth = 0.5) +
  scale_fill_gradient(low = "white", high = "#005F61",
                      guide_colorbar(frame.color = "black", frame.linewidth = 0.5)) +
  labs(title = "Differences in intrastate predicted turnout among age groups",
       subtitle = "Colors represent variance in turnout odds",
       caption = "Ages broken down by 18-29, 30-44, 45-64, and 65+\n and using 2010-2020 CPS Voting Supplement data.") +
  theme_void() +
  theme(legend.position = "none")

age_plot


states_educ_map <- us_map(regions = "states") |>
  full_join(state_educ_var, by = c("full" = "STATE"))

educ_plot <- ggplot(data = states_educ_map, aes(x = x, y = y, group = group)) +
  geom_polygon(aes(fill = cum_var), color = "black", linewidth = 0.5) +
  scale_fill_gradient(low = "white", high = "#2E1A47",
                      guide_colorbar(frame.color = "black", frame.linewidth = 0.5)) +
  labs(title = "Differences in intrastate predicted turnout among educational attainment groups",
       subtitle = "Colors represent variance in turnout odds",
       caption = "Education broken down by no HS diploma, HS diploma,\nsome college or bachelor's, and advanced degree\n and using 2010-2020 CPS Voting Supplement data.") +
  theme_void() +
  theme(legend.position = "none")

educ_plot

#diffany map
states_diffany_map <- us_map(regions = "states") |>
  full_join(state_diffany_var, by = c("full" = "STATE"))

diffany_plot <- ggplot(data = states_diffany_map, aes(x = x, y = y, group = group)) +
  geom_polygon(aes(fill = cum_var), color = "black", linewidth = 0.5) +
  scale_fill_gradient(low = "white", high = "#003B1B",
                      guide_colorbar(frame.color = "black", frame.linewidth = 0.5)) +
  labs(title = "Differences in intrastate predicted turnout between disabled and non-disabled groups",
       subtitle = "Colors represent variance in turnout odds",
       caption = "Using Census disability classification and\n and 2010-2020 CPS Voting Supplement data.") +
  theme_void() +
  theme(legend.position = "none")

diffany_plot
```
