---
title: "model-building"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#load libraries
library(tidyverse)
library(cpsvote)
library(srvyr)
library(rstanarm)
library(bayesplot)
library(purrr)
library(tidycensus)
```

```{r}
#load VEP data
vep_20 <- read_csv("data/2020 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%","", total_ballot)) / 100)

vep_18 <- read_csv("data/2018 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%","", total_ballot)) / 100)

vep_16 <- read_csv("data/2016 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%","", total_ballot)) / 100)

vep_14 <- read_csv("data/2014 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%","", total_ballot)) / 100)

vep_12 <- read_csv("data/2012 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%","", total_ballot)) / 100)

vep_10 <- read_csv("data/2010 VEP.csv") |>
  filter(STATE != "United States") |>
  mutate(total_ballot = as.numeric(gsub("%","", total_ballot)) / 100)
```

```{r}
#load data
data_20 <- read_csv("data/cps_csv_files/2020 cps.csv")
data_12 <- read_csv("data/cps_csv_files/2012 cps.csv")
data_18 <- read_csv("data/cps_csv_files/2018 cps.csv")
```

```{r}
#clean 2018 data
data_18 <- data_18 |> mutate(
  REGION = recode(REGION, 
    "11" = "Northeast",
    "12" = "Northeast",
    "21" = "Midwest",
    "22" = "Midwest",
    "31" = "South", 
    "32" = "South", 
    "33" = "South", 
    "41" = "West",
    "42" = "South", 
    .default = "Other"), 
  SEX = recode(SEX,
    "1" = "Male", 
    "2" = "Female",
    .default = "NIU"),
  RACE = case_when(
    RACE == 100 ~ "White", 
    RACE == 200 ~ "Black", 
    RACE == 300 ~ "AmIn", 
    RACE == 700 ~ "Other",
    RACE %in% c(650, 651, 652, 809) ~ "AAPI", 
    .default = "Multi-racial"),
  HISPAN = recode(HISPAN,
    "000" = "Not Hispanic",            
    "901" =  "NIU", 
    "902" =  "NIU", 
    .default = "Hispanic"), 
  DIFFANY = recode(DIFFANY,
    "1" = "No", 
    "2" = "Yes",
    "0" = "NIU"), 
  SCHLCOLL = recode(SCHLCOLL, 
    "3" = "College", 
    "4" = "College",
    "5" = "Non-College",
    "1" = "HS", 
    "2" = "HS", 
    "0" = "NIU"),
   EDUC = case_when(EDUC >= 999 ~ "Unknown", 
                                EDUC >= 120 ~ "Beyond Bachelors", 
                                EDUC >= 80 ~ "Some College", 
                                EDUC == 73 ~ "HS", 
                                EDUC >= 2 ~ "No HS", 
                                EDUC <= 1 ~ "NIU"),
  AGE = case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+"),
  VOTED = recode(VOTED,
                 "2" = "Yes",
                 "1" = "No",
                 .default = NULL)) |>
  mutate(VOTED = factor(VOTED, levels = c("Yes", "No"))) |>
  drop_na(VOTED) |>
  select(REGION, STATEFIP, AGE, SEX, RACE, HISPAN, EDUC, DIFFANY, SCHLCOLL, VOTED, VOSUPPWT)


ids <- c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,44,45,46,47,48,49,50,51,53,54,55,56)
states <- c("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming")

states_list <- list("Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District of Columbia", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming")

states_df <- data.frame(ids, as.factor(states))

names(states_df) <- c('STATEFIP', 'STATE')

data_18 <- merge(data_18, states_df, by="STATEFIP", all = FALSE)


#region: recode into 1-4
#region: 11, 12 = Northeast, 21, 22 = Midwest, 31-33 = South, 41, 42 = West
#statefip : recode
#sex: recode 1 = male, 2 = female, 9 = NIU
#race: 100 = White, 200 = Black, 300 = AmIn, 650-652 and 809 = AAPI, 700 = Other, 801-808 = Biracial
#hispan: 000 = Not Hispanic, 100, 102, 103, 104, 108, 109, 200, 300, 400, 500, 600, 710,  611, 612 = Hispanic, 901 and 902 = NIU
#diffany: 1 = No, 2 = Yes, 0 = NIU
#educ: recode
#schlcoll: 3,4, = College, 1,2 = HS, 5 = Non-College, 0 = NIU

```

```{r}
#create sample data table

data_18_sample <- data_18 |>
  group_by(STATE, RACE, AGE, HISPAN, DIFFANY, EDUC, VOTED) |>
  count()
```

```{r}
#build post-strat table for 2018
pums_vars_2018 <- pums_variables |>
  distinct(var_code, var_label, data_type, level)

pums_test <- get_pums(variables = c("RAC1P", "SCHL", "HISP", "DIS", "AGEP"),
                      survey = "acs1", year = "2018", state = "all", recode = TRUE)


pums_18_test <- pums_test |>
  rename(HISPAN = HISP_label, RACE = RAC1P_label, EDUC = SCHL_label, STATE = ST_label, AGE = AGEP, DIFFANY = DIS_label) |>
  filter(RACE != 8) |>
  mutate(HISPAN = if_else(HISPAN == "Not Spanish/Hispanic/Latino", "Not Hispanic", "Hispanic"),
         EDUC = if_else(SCHL < 16 | SCHL == "bb", "No HS",
                        if_else(SCHL < 18, "HS", 
                                if_else(SCHL < 22, "Some College", "Beyond Bachelors"))),
         AGE =  case_when(AGE < 30 ~ "18-29", 
                  AGE < 45 ~ "30-44",
                  AGE < 65 ~ "45-64",
                  .default = "65+"),
         RACE = case_when(RAC1P == 1 ~ "White",
                          RAC1P == 2 ~ "Black",
                          RAC1P == 3 | RAC1P == 4 | RAC1P == 5 ~ "AmIn",
                          RAC1P == 6 | RAC1P == 7 ~ "AAPI",
                          RAC1P == 9 ~ "Multi-racial"),
         DIFFANY = if_else(DIS == 1, "Yes", "No"),
         STATE = str_sub(STATE, end = -4)) |>
  select(SERIALNO, SPORDER, AGE, HISPAN, STATE, RACE, EDUC, DIFFANY) |>
  drop_na()

data_18_poststrat <- pums_18_test |>
  group_by(STATE, RACE, AGE, HISPAN, DIFFANY, EDUC) |>
  count()
```

```{r}
#preliminary analysis: graph proportion of voting

vote_totals_2018 <- data_18 |>
  group_by(STATE) |>
  summarize(total_votes = sum(VOTED == "Yes"))

vote_pop_2018 <- data_18 |>
  group_by(STATE) |>
  summarize(total_sample = n())

turnout_df_2018 <- vote_totals_2018 |>
  left_join(vote_pop_2018, by = "STATE") |>
  mutate(turnout_rate = total_votes/total_sample)

ggplot(data = turnout_df, aes(x = STATE, y = turnout_rate)) +
  geom_point() +
  geom_line(aes(group = 1)) +
  theme(axis.text.x = element_text(angle = 45))
```

```{r}
#model fitting
fit <- stan_glmer(VOTED ~ (1 | STATE) + (1 | RACE) + factor(HISPAN) + (1 | EDUC) + (1 | AGE) + factor(DIFFANY),
  family = binomial(link = "logit"),
  data = data_18,
  prior = normal(0, 1, autoscale = TRUE),
  prior_covariance = decov(scale = 0.50),
  adapt_delta = 0.99,
  refresh = 0,
  seed = 1010)
```